# 
# Synthesis run script generated by Vivado
# 

set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.cache/wt [current_project]
set_property parent.project_path C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/Test/Ips/MPC_Trigger
  c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/ip_repo/AXI_to_Signal16_1.0
  c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/ip_repo/AXI_to_Signal_1.0
  c:/Users/ga53xem/IIoT-EDDP/HLS/ARTY_Z7_FULL/ip_lib
  c:/Users/ga53xem/FCSMPC_2.0/solution2
  c:/Users/ga53xem/P_Controller/solution2
} [current_project]
set_property ip_output_repo c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/hdl/zsys_wrapper.vhd
add_files C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/zsys.bd
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_axi_datamover_0_0/zsys_axi_datamover_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_axi_datamover_0_0/zsys_axi_datamover_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_axi_datamover_0_0/zsys_axi_datamover_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_processing_system7_0_0/zsys_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_Clarke_Direct_0_0/constraints/Clarke_Direct_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_Clarke_Inverse_0_0/constraints/Clarke_Inverse_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_Filters_0_0/constraints/Filters_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_Flux_PI_Control_0/constraints/PI_Control_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_Park_Direct_0_0/constraints/Park_Direct_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_Park_Inverse_0_0/constraints/Park_Inverse_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_RPM_PI_Control_0/constraints/PI_Control_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_SVPWM_0_0/constraints/SVPWM_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_Torque_PI_Control_0/constraints/PI_Control_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_axis_broadcaster_0_0/zsys_axis_broadcaster_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0/zsys_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_axis_subset_converter_0_0/zsys_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_1_2/zsys_axis_data_fifo_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_axis_data_fifo_1_2/zsys_axis_data_fifo_1_2/zsys_axis_data_fifo_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_FCSMPC_0_1/constraints/FCSMPC_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_xbar_0/zsys_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_fit_timer_0_0/zsys_fit_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_1/bd_1/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_1/bd_1/ip/ip_0/bd_3489_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_1/bd_1/bd_3489_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_2/zsys_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_1/zsys_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_3/zsys_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/ip/zsys_auto_pc_0/zsys_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/zsys_ooc.xdc]
set_property is_locked true [get_files C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/sources_1/bd/zsys/zsys.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/constrs_1/imports/constraints/Arty_Z7.xdc
set_property used_in_implementation false [get_files C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/constrs_1/imports/constraints/Arty_Z7.xdc]

read_xdc C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/constrs_1/imports/constraints/vivado_target.xdc
set_property used_in_implementation false [get_files C:/Users/ga53xem/IIoT-EDDP/myWS/VivadoProjects/my_FOC/my_FOC.srcs/constrs_1/imports/constraints/vivado_target.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zsys_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef zsys_wrapper.dcp

catch { report_utilization -file zsys_wrapper_utilization_synth.rpt -pb zsys_wrapper_utilization_synth.pb }
